[checkpoints.c3d_c3d_ucf101]
model = "c3d"
backbone = "c3d"
weights_dataset = "ucf101"
repo_id = "maxv65/vcr-bench"
filename = "c3d_ucf101_mmaction.pth"
revision = "main"
local_subdir = "vcr_bench/models/c3d/checkpoints"

[checkpoints.x3d_m_kinetics400]
model = "x3d"
backbone = "m"
weights_dataset = "kinetics400"
repo_id = "maxv65/vcr-bench"
filename = "x3d_m_kinetics400_mmaction.pth"
revision = "main"
local_subdir = "vcr_bench/models/x3d/checkpoints"

[checkpoints.timesformer_base_kinetics400]
model = "timesformer"
backbone = "base"
weights_dataset = "kinetics400"
repo_id = "maxv65/vcr-bench"
filename = "timesformer_vit_base_p16_kinetics400_mmaction.pth"
revision = "main"
local_subdir = "vcr_bench/models/timesformer/checkpoints"

[checkpoints.videomae_base_kinetics400]
model = "videomae"
backbone = "base"
weights_dataset = "kinetics400"
repo_id = "maxv65/vcr-bench"
filename = "videomae_vit_base_p16_kinetics400_mmaction.pth"
revision = "main"
local_subdir = "vcr_bench/models/videomae/checkpoints"

[checkpoints.videomaev2_base_kinetics400]
model = "videomaev2"
backbone = "base"
weights_dataset = "kinetics400"
repo_id = "maxv65/vcr-bench"
filename = "videomaev2_vit_base_p16_kinetics400_mmaction.pth"
revision = "main"
local_subdir = "vcr_bench/models/videomaev2/checkpoints"

[checkpoints.videoswin_base_kinetics400]
model = "videoswin"
backbone = "base"
weights_dataset = "kinetics400"
repo_id = "maxv65/vcr-bench"
filename = "videoswin_base_p244_kinetics400_mmaction.pth"
revision = "main"
local_subdir = "vcr_bench/models/videoswin/checkpoints"

[checkpoints.slowfast_r101_kinetics400]
model = "slowfast"
backbone = "r101"
weights_dataset = "kinetics400"
repo_id = "maxv65/vcr-bench"
filename = "slowfast_r101_kinetics400_mmaction.pth"
revision = "main"
local_subdir = "vcr_bench/models/slowfast/checkpoints"

[checkpoints.slowonly_r50_kinetics400]
model = "slowonly"
backbone = "r50"
weights_dataset = "kinetics400"
repo_id = "maxv65/vcr-bench"
filename = "slowonly_r50_kinetics400_mmaction.pth"
revision = "main"
local_subdir = "vcr_bench/models/slowonly/checkpoints"

[checkpoints.mvitv2_base_kinetics400]
model = "mvitv2"
backbone = "base"
weights_dataset = "kinetics400"
repo_id = "maxv65/vcr-bench"
filename = "mvit_base_p244_kinetics400_mmaction.pth"
revision = "main"
local_subdir = "vcr_bench/models/mvitv2/checkpoints"

[checkpoints.r2plus1d_r34_kinetics400]
model = "r2plus1d"
backbone = "r34"
weights_dataset = "kinetics400"
repo_id = "maxv65/vcr-bench"
filename = "r2plus1d_r34_kinetics400_mmaction.pth"
revision = "main"
local_subdir = "vcr_bench/models/r2plus1d/checkpoints"

[checkpoints.i3d_r50_kinetics400]
model = "i3d"
backbone = "r50"
weights_dataset = "kinetics400"
repo_id = "maxv65/vcr-bench"
filename = "i3d_r50_kinetics400_mmaction.pth"
revision = "main"
local_subdir = "vcr_bench/models/i3d/checkpoints"

[checkpoints.i3dnonlocal_r50_kinetics400]
model = "i3dnonlocal"
backbone = "r50"
weights_dataset = "kinetics400"
repo_id = "maxv65/vcr-bench"
filename = "i3dnonlocal_r50_kinetics400_mmaction.pth"
revision = "main"
local_subdir = "vcr_bench/models/i3dnonlocal/checkpoints"

[checkpoints.tsm_r50_kinetics400]
model = "tsm"
backbone = "r50"
weights_dataset = "kinetics400"
repo_id = "maxv65/vcr-bench"
filename = "tsm_r50_kinetics400_mmaction.pth"
revision = "main"
local_subdir = "vcr_bench/models/tsm/checkpoints"

[checkpoints.tsmnonlocal_r50_kinetics400]
model = "tsmnonlocal"
backbone = "r50"
weights_dataset = "kinetics400"
repo_id = "maxv65/vcr-bench"
filename = "tsmnonlocal_r50_kinetics400_mmaction.pth"
revision = "main"
local_subdir = "vcr_bench/models/tsmnonlocal/checkpoints"

[checkpoints.uniformer_base_kinetics400]
model = "uniformer"
backbone = "base"
weights_dataset = "kinetics400"
repo_id = "maxv65/vcr-bench"
filename = "uniformer_base_kinetics400_mmaction.pth"
revision = "main"
local_subdir = "vcr_bench/models/uniformer/checkpoints"

[checkpoints.uniformerv2_base_kinetics400]
model = "uniformerv2"
backbone = "base"
weights_dataset = "kinetics400"
repo_id = "maxv65/vcr-bench"
filename = "uniformerv2_base_kinetics400_mmaction.pth"
revision = "main"
local_subdir = "vcr_bench/models/uniformerv2/checkpoints"

[checkpoints.actionclip_vit_b16_kinetics400]
model = "actionclip"
backbone = "vit_b16"
weights_dataset = "kinetics400"
repo_id = "vcr-bench/checkpoints-actionclip"
filename = "actionclip_vit_b16_32f_kinetics400_mmaction.pth"
revision = "main"
local_subdir = "vcr_bench/models/actionclip/checkpoints"

[checkpoints.internvideo_base_kinetics400]
model = "internvideo"
backbone = "base"
weights_dataset = "kinetics400"
repo_id = "vcr-bench/checkpoints-internvideo"
filename = "internvideo_vit_base_p16_kinetics400.bin"
revision = "main"
local_subdir = "vcr_bench/models/internvideo/checkpoints"

[checkpoints.amd_vitb_kinetics400]
model = "amd"
backbone = "vitb"
weights_dataset = "kinetics400"
repo_id = "maxv65/vcr-bench"
filename = "amd_vitb_k400_finetune_90e.pth"
revision = "main"
local_subdir = "vcr_bench/models/amd/checkpoints"

[checkpoints.ila_vit_b16_kinetics400]
model = "ila"
backbone = "vit_b16"
weights_dataset = "kinetics400"
repo_id = "maxv65/vcr-bench"
filename = "ila_k400_B_16_8_rel.pth"
revision = "main"
local_subdir = "vcr_bench/models/ila/checkpoints"

[checkpoints.internvideo2_vit_1b_p14_kinetics400]
model = "internvideo2"
backbone = "vit_1b_p14"
weights_dataset = "kinetics400"
repo_id = "maxv65/vcr-bench"
filename = "internvideo2_1B_ft_k710_ft_k400_f16.pth"
revision = "main"
local_subdir = "vcr_bench/models/internvideo2/checkpoints"

[checkpoints.onepeace_vit_l40_kinetics400]
model = "onepeace"
backbone = "vit_l40"
weights_dataset = "kinetics400"
repo_id = "maxv65/vcr-bench"
filename = "onepeace_video_k400.pth"
revision = "main"
local_subdir = "vcr_bench/models/onepeace/checkpoints"

[checkpoints.tadaformer_large_14_kinetics400]
model = "tadaformer"
backbone = "large_14"
weights_dataset = "kinetics400"
repo_id = "maxv65/vcr-bench"
filename = "tadaformer_l14_clip+k710_k400_64f_89.9.pyth"
revision = "main"
local_subdir = "vcr_bench/models/tadaformer/checkpoints"

[checkpoints.umt_vit_large_p16_kinetics400]
model = "umt"
backbone = "vit_large_p16"
weights_dataset = "kinetics400"
repo_id = "maxv65/vcr-bench"
filename = "umt_l16_ptk710_ftk710_ftk400_f8_res224.pth"
revision = "main"
local_subdir = "vcr_bench/models/umt/checkpoints"
