[datasets.kinetics400.k400_val]
repo_id = "maxv65/vcr-bench"
filename = "k400_val.zip"
annotations_filename = "k400_val.csv"
labels_filename = "k400_label_map_k400.txt"
revision = "main"
extract_subdir = "k400_val"
video_root = "."
annotations = "annotations/k400_val.csv"
labels = "annotations/k400_label_map_k400.txt"
split = "val"

[datasets.kinetics400.k400_test]
repo_id = "maxv65/vcr-bench"
filename = "k400_test.zip"
annotations_filename = "k400_test.csv"
labels_filename = "k400_label_map_k400.txt"
revision = "main"
extract_subdir = "k400_test"
video_root = "."
annotations = "annotations/k400_test.csv"
labels = "annotations/k400_label_map_k400.txt"
split = "test"

[datasets.kinetics400.kinetics400_mini_val]
repo_id = "maxv65/vcr-bench"
filename = "k400_val.zip"
annotations_filename = "k400_val.csv"
labels_filename = "k400_label_map_k400.txt"
revision = "main"
extract_subdir = "k400_val"
video_root = "."
annotations = "annotations/k400_val.csv"
labels = "annotations/k400_label_map_k400.txt"
split = "val"

[datasets.kinetics400.kinetics400_mini_test]
repo_id = "maxv65/vcr-bench"
filename = "k400_test.zip"
annotations_filename = "k400_test.csv"
labels_filename = "k400_label_map_k400.txt"
revision = "main"
extract_subdir = "k400_test"
video_root = "."
annotations = "annotations/k400_test.csv"
labels = "annotations/k400_label_map_k400.txt"
split = "test"
