# Dataset subset manifests.
#
# Raw video files for copyrighted datasets (Kinetics-400, UCF-101,
# Something-Something V2, ...) are NOT redistributed by VCR-Bench. Those subsets are
# left with `redistributable = false`: the adapters resolve annotations/labels, but the
# videos must be supplied by the user via --video-root (see docs/datasets.md).
#
# Only subsets explicitly flagged `redistributable = true` auto-download their video
# archive. The `demo` subset below is a small set of real Kinetics clips whose source
# YouTube videos are Creative Commons (CC BY 3.0), so they are redistributable with
# attribution; it carries real ground-truth labels. Intended for demos / smoke tests, not
# for reproducing benchmark numbers. See docs/demo_dataset.md and
# scripts/select_kinetics_cc.py (build) — scripts/build_demo_dataset.py is a CC0 alternative.

[datasets.kinetics400.demo]
redistributable = true
repo_id = "maxv65/vcr-bench"
filename = "k400_demo_cc0.zip"
annotations_filename = "k400_demo_cc0.csv"
labels_filename = "k400_label_map_k400.txt"
revision = "main"
extract_subdir = "k400_demo_cc0"
video_root = "."
annotations = "annotations/k400_demo_cc0.csv"
labels = "annotations/k400_label_map_k400.txt"
split = "test"

[datasets.kinetics400.k400_val]
redistributable = false
repo_id = "maxv65/vcr-bench"
filename = "k400_val.zip"
annotations_filename = "k400_val.csv"
labels_filename = "k400_label_map_k400.txt"
revision = "main"
extract_subdir = "k400_val"
video_root = "."
annotations = "annotations/k400_val.csv"
labels = "annotations/k400_label_map_k400.txt"
split = "val"

[datasets.kinetics400.k400_test]
redistributable = false
repo_id = "maxv65/vcr-bench"
filename = "k400_test.zip"
annotations_filename = "k400_test.csv"
labels_filename = "k400_label_map_k400.txt"
revision = "main"
extract_subdir = "k400_test"
video_root = "."
annotations = "annotations/k400_test.csv"
labels = "annotations/k400_label_map_k400.txt"
split = "test"

[datasets.kinetics400.kinetics400_mini_val]
redistributable = false
repo_id = "maxv65/vcr-bench"
filename = "k400_val.zip"
annotations_filename = "k400_val.csv"
labels_filename = "k400_label_map_k400.txt"
revision = "main"
extract_subdir = "k400_val"
video_root = "."
annotations = "annotations/k400_val.csv"
labels = "annotations/k400_label_map_k400.txt"
split = "val"

[datasets.kinetics400.kinetics400_mini_test]
redistributable = false
repo_id = "maxv65/vcr-bench"
filename = "k400_test.zip"
annotations_filename = "k400_test.csv"
labels_filename = "k400_label_map_k400.txt"
revision = "main"
extract_subdir = "k400_test"
video_root = "."
annotations = "annotations/k400_test.csv"
labels = "annotations/k400_label_map_k400.txt"
split = "test"
